name: 📻 Callsign Registration
description: Register or update your amateur radio callsign in the MY-Callbook directory
title: "[CALLSIGN] "
labels: ["callsign-submission"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📻 Malaysian Amateur Radio Callbook Registration
        
        Thank you for registering your callsign! Please fill in the details below.
        Your submission will be reviewed and added to the directory.
        
        **Privacy Notice:** By submitting this form, you agree to have this information published publicly in the directory.

  - type: input
    id: callsign
    attributes:
      label: Callsign
      description: Your Malaysian amateur radio callsign (e.g., 9M2ABC, 9W2XYZ)
      placeholder: "9M2ABC"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      description: Your name as registered with MCMC
      placeholder: "AHMAD BIN ALI"
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Location (State)
      description: Select your state
      options:
        - JOHOR
        - KEDAH
        - KELANTAN
        - MELAKA
        - NEGERI SEMBILAN
        - PAHANG
        - PERAK
        - PERLIS
        - PULAU PINANG
        - SABAH
        - SARAWAK
        - SELANGOR
        - TERENGGANU
        - KUALA LUMPUR
        - LABUAN
        - PUTRAJAYA
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email (Optional)
      description: Your contact email
      placeholder: "callsign@example.com"
    validations:
      required: false

  - type: input
    id: phone
    attributes:
      label: Phone (Optional)
      description: Your contact phone number
      placeholder: "+60123456789"
    validations:
      required: false

  - type: input
    id: address
    attributes:
      label: Address (Optional)
      description: Your mailing address
      placeholder: "123, Jalan Radio, 50000 Kuala Lumpur"
    validations:
      required: false

  - type: input
    id: website
    attributes:
      label: Website (Optional)
      description: Your personal or club website URL
      placeholder: "https://example.com"
    validations:
      required: false

  - type: input
    id: facebook
    attributes:
      label: Facebook (Optional)
      description: Your Facebook profile URL
      placeholder: "https://facebook.com/yourprofile"
    validations:
      required: false

  - type: input
    id: qrz
    attributes:
      label: QRZ.com Profile (Optional)
      description: Your QRZ.com profile URL
      placeholder: "https://www.qrz.com/db/9M2ABC"
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Agreement
      description: Please confirm the following
      options:
        - label: I confirm that I am a licensed Malaysian amateur radio operator
          required: true
        - label: I agree to have this information published publicly in the directory
          required: true
